version: '3'
services:
  client:
    image: aistated/net.pannenko.cicd.client1
    container_name: ${COMPOSE_PROJECT_NAME}-client1
    environment:
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      VIRTUAL_HOST: ${COMPOSE_PROJECT_NAME}.localhost
    networks:
      default:
        aliases:
          - client
      ops_infra-network:
      ops_client-proxy-network:
      ops_env-network:
  server1:
    image: aistated/net.pannenko.cicd.server1
    container_name: ${COMPOSE_PROJECT_NAME}-server1
    environment:
      VIRTUAL_HOST: ${COMPOSE_PROJECT_NAME}.localhost
      SPRING_PROFILES_ACTIVE: ${COMPOSE_PROJECT_NAME}
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"label":"${COMPOSE_PROJECT_NAME}"}}}}'
    networks:
      default:
        aliases:
          - server1
      ops_infra-network:
      ops_server-proxy-network:
      ops_env-network:
networks:
  ops_env-network:
    external:
      name: ops_${ENV}-network
  ops_infra-network:
    external: true
  ops_client-proxy-network:
    external: true
  ops_server-proxy-network:
    external: true